import { Emoji, Description } from "./helpers";
import iSee from '../assets/emojis/iSee.png';
import PepeHands from '../assets/emojis/PepeHands.png';
import Sadeg from '../assets/emojis/Sadeg.png';
import monkaOMEGA from '../assets/emojis/monkaOMEGA.png';

const rawVideos = [
  {
    embedId: 'va810QKC1S0',
    score: 58, 
    tags: ['инструментальная', 'грустная', 'спокойная', 'классическая'],
    description: null,
  },
  {
    embedId: '2Od7QCsyqkE',
    score: 71,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'mcywsWmHEVc',
    score: 89,
    tags: ['japanese', 'веселая', 'спокойная'],
    description: null,
  },
  {
    embedId: 'FQs9cV0jycg',
    score: 86,
    tags: ['инструментальная', 'xi', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'jO4fTcziVRM',
    score: 80,
    tags: ['инструментальная', 'xi', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'U4LcyjRFDds',
    score: 72,
    tags: ['японская', 'вокалоид'],
    description: null,
  },
  {
    embedId: '7EEUU-yIN5c',
    score: 76,
    tags: ['японская', 'вокалоид', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'Yzjum7CgQqw',
    score: 77,
    tags: ['инструментальная', 'электронная', 'активная'],
    description: null,
  },
  {
    embedId: 'k-3y2LVF_SE',
    score: 100,
    tags: ['инструментальная', 'xi', 'электронная', 'активная', 'веселая', 'хардкор/спидкор'],
    description: (
      <Description>
        Узнал из osu!, можно сказать, что это гимн этой игры для меня.
        Один из самых любимых треков.
        Помню всегда пытался пройти <a target="_blank" href="https://www.youtube.com/watch?v=VsYLIg67pYo">эту карту</a>
      </Description>
    ),
  },
  {
    embedId: 'EmWOznX2uUQ',
    score: 73,
    tags: ['english', 'rock'],
    description: null,
  },
  {
    embedId: 'iQp9iud9u0I',
    score: 70,
    tags: ['инструментальная', 'активная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'lvRw5Kjx31o',
    score: 68,
    tags: ['японская', 'веселая'],
    description: null,
  },
  {
    embedId: 'wExQLV7Ndps',
    score: 83,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'BgQ8sa0HPtQ',
    score: 80,
    tags: ['японская', 'веселая', 'активная', 'кельтская', 'akatsuki records'],
    description: (
      <Description>
        Очень прикольная и уникальная песня.
      </Description>
    ),
  },
  {
    embedId: 'q-v-a-NFH-Q',
    score: 77,
    tags: ['english', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'IWEpkRoxK0o',
    score: 85,
    tags: ['инструментальная', 'электронная', 'хардкор/спидкор', 'активная'],
    description: null,
  },
  {
    embedId: 'Sq_q5MIIYX4',
    score: 67,
    tags: ['инструментальная', 'активная', 'веселая', 'кельтская'],
    description: null,
  },
  {
    embedId: 'w0dU7NyfN_A',
    score: 79,
    tags: ['инструментальная', 'электронная', 'хардкор/спидкор', 'активная'],
    description: null,
  },
  {
    embedId: 'HbNUR1P0fTM',
    score: 70,
    tags: ['инструментальная', 'электронная', 'хардкор/спидкор', 'активная'],
    description: null,
  },
  {
    embedId: 'EJYKsY0Vcts',
    score: 81,
    tags: ['японская', 'веселая'],
    description: null,
  },
  {
    embedId: 'lkicMsn-s_8',
    score: 96,
    tags: ['инструментальная', 'метал', 'активная'],
    description: null,
  },
  {
    embedId: 'f3ESZSrKvkI',
    score: 70,
    tags: ['инструментальная', 'phyxinon', 'грустная', 'классическая'],
    description: null,
  },
  {
    embedId: 'Pn7dCgtwX2c',
    score: 60,
    tags: ['японская', 'активная'],
    description: null,
  },
  {
    embedId: 'M-r44DVnbSE',
    score: 92,
    tags: ['инструментальная', 'грустная', 'активная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'ZwfjS5CvedM',
    score: 84,
    tags: ['японская', 'спокойная', 'kalafina', 'yuki kajiura'],
    description: null,
  },
  {
    embedId: 'N_SWfKjvlvw',
    score: 84,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: '-wILF0YwvNM',
    score: 78,
    tags: ['японская', 'спокойная', 'kalafina', 'yuki kajiura'],
    description: null,
  },
  {
    embedId: 'srhni4w2TbI',
    score: 80,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'Kkgp1-fHn6Y',
    score: 80,
    tags: ['инструментальная', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'PstkKL72mw0',
    score: 90,
    tags: ['японская', 'love solfege', 'кельтская', 'спокойная'],
    description: null,
  },
  {
    embedId: '6IkuV_lZtiI',
    score: 80,
    tags: ['инструментальная', 'грустная', 'спокойная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'b1bXu0XZDlU',
    score: 84,
    tags: ['японская', 'спокойная', 'kalafina', 'yuki kajiura'],
    description: null,
  },
  {
    embedId: 'aEHxqBHCkFc',
    score: 86,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'UWwzmed9Z5U',
    score: 76,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'XbRPOR19p_c',
    score: 68,
    tags: ['японская', 'активная', 'веселая'],
    description: (
      <Description>
        Очень нравится часть с 0:58.
      </Description>
    ),
  },
  {
    embedId: 'U1oeOZVtA84',
    score: 80,
    tags: ['японская', 'вокалоид', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'oozQ4yV__Vw',
    score: 86,
    tags: ['english', 'активная', 'веселая'],
    description: (
      <Description>
        Скорее всего, это песня была дольше всех других в моем плейлисте.
      </Description>
    ),
  },
  {
    embedId: 'dkCMpHF27fo',
    score: 82,
    tags: ['японская'],
    description: null,
  },
  {
    embedId: '6fILxnBH1Tg',
    score: 80,
    tags: ['инструментальная', 'активная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'JxFUY7Ka8e0',
    score: 90,
    tags: ['японская', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: 'eJhCAnjz8ZA',
    score: 74,
    tags: ['японская', 'вокалоид', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: '8nxuNiRJKRg',
    score: 77,
    tags: ['японская', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'swZd3u6voNE',
    score: 88,
    tags: ['японская', 'love solfege', 'спокойная'],
    description: null,
  },
  {
    embedId: 'SrEHyYlJjVA',
    score: 90,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'DN-Dcwq4i2g',
    score: 80,
    tags: ['инструментальная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'S-Nll_HapuU',
    score: 77,
    tags: ['инструментальная', 'спокойная', 'phyxinon', 'классическая'],
    description: null,
  },
  {
    embedId: 't4XycIIfA6A',
    score: 94,
    tags: ['инструментальная', 'активная', 'оркестровая'],
    description: (
      <Description>
        С 2:03 вообще крутяк!
      </Description>
    ),
  },
  {
    embedId: 'W6I1xm49Lpw',
    score: 72,
    tags: ['японская', 'спокойная'],
    description: null,
  },
  {
    embedId: 'dPLKc5tdvo0',
    score: 90,
    tags: ['японская', 'спокойная', 'love solfege'],
    description: null,
  },
  {
    embedId: 'wDIzGjLwKBM',
    score: 89,
    tags: ['японская', 'спокойная', 'love solfege'],
    description: null,
  },
  {
    embedId: 'ZZvJY7_gyfw',
    score: 78,
    tags: ['японская', 'активная', 'yousei teikoku'],
    description: null,
  },
  {
    embedId: 'vw2-PDXs2zY',
    score: 87,
    tags: ['японская', 'спокойная', 'love solfege'],
    description: null,
  },
  {
    embedId: 'N_O7wkUmLqs',
    score: 80,
    tags: ['инструментальная', 'активная'],
    description: null,
  },
  {
    embedId: 'bE0hDymkLsQ',
    score: 80,
    tags: ['японская', 'спокойная', 'love solfege'],
    description: null,
  },
  {
    embedId: 'bAZuZjMD7lE',
    score: 92,
    tags: ['японская', 'спокойная', 'kalafina', 'yuki kajiura'],
    description: null,
  },
  {
    embedId: 'ady--PNMsfI',
    score: 77,
    tags: ['спокойная'],
    description: null,
  },
  {
    embedId: '4oPM8zTeois',
    score: 70,
    tags: ['инструментальная', 'грустная', 'спокойная', 'phyxinon', 'классическая'],
    description: null,
  },
  {
    embedId: '5kKnrjeDUqw',
    score: 81,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'IB1URcYIaOE',
    score: 80,
    tags: ['english', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'xHq-TEluOrM',
    score: 84,
    tags: ['инструментальная', 'спокойная', 'грустная', 'оркестровая'],
    description: (
      <Description>
        Кто за нек(г)ров играл??? <br /> <Emoji src={iSee} />
      </Description>
    ),
  },
  {
    embedId: 'qO8AoYPnr68',
    score: 69,
    tags: ['грустная', 'спокойная', 'оркестровая'],
    description: null,
  },
  {
    embedId: '-RAeuWxOif4',
    score: 88,
    tags: ['японская', 'веселая', 'активная', 'электронная', 'вокалоид'],
    description: null,
  },
  {
    embedId: 'zycqjvKFiHU',
    score: 89,
    tags: ['японская', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: '4_ANxTOG_Xk',
    score: 67,
    tags: ['инструментальная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'pTRgr9IWLnY',
    score: 76,
    tags: ['yuki kajiura', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'by_dL99tndw',
    score: 83,
    tags: ['японская', 'вокалоид', 'веселая', 'спокойная'],
    description: null,
  },
  {
    embedId: 'yql9xh5UaIw',
    score: 62,
    tags: ['english', 'nomy', 'активная', 'грустная', 'rock'],
    description: null,
  },
  {
    embedId: 'Bjadoqjdz2c',
    score: 80,
    tags: ['english', 'nomy', 'активная', 'rock'],
    description: null,
  },
  {
    embedId: '5nReJMJGrRE',
    score: 84,
    tags: ['инструментальная', 'yuki kajiura', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'FqCw7gCTZQs',
    score: 80,
    tags: ['японская', 'спокойная'],
    description: null,
  },
  {
    embedId: 'fr26k_KusS4',
    score: 70,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'cOe9RPqg1GE',
    score: 84,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'nSDgHBxUbVQ',
    score: 81,
    tags: ['english', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'M92c6pl10u0',
    score: 78,
    tags: ['японская', 'вокалоид', 'веселая', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'F8t5mR6AmK8',
    score: 68,
    tags: ['спокойная'],
    description: null,
  },
  {
    embedId: 'XTedaWpPjto',
    score: 80,
    tags: ['english', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: '_4BLiOP1aaY',
    score: 68,
    tags: ['японская', 'веселая'],
    description: null,
  },
  {
    embedId: 'BG746QmRgqk',
    score: 90,
    tags: ['японская', 'rigël theatre', 'кельтская', 'веселая'],
    description: null,
  },
  {
    embedId: '_IY95itIKis',
    score: 90,
    tags: ['японская', 'rigël theatre', 'кельтская', 'веселая'],
    description: null,
  },
  {
    embedId: 'pV1DT5JlRlc',
    score: 91,
    tags: ['инструментальная', 'rigël theatre', 'кельтская', 'веселая', 'спокойная'],
    description: null,
  },
  {
    embedId: 'kv4UD4ICd_0',
    score: 93,
    tags: ['инструментальная', 'rigël theatre', 'кельтская', 'веселая', 'спокойная'],
    description: null,
  },
  {
    embedId: '-I--cdqDbdU',
    score: 89,
    tags: ['инструментальная', 'rigël theatre', 'кельтская', 'веселая', 'спокойная'],
    description: null,
  },
  {
    embedId: '1bJEjHk0BGk',
    score: 83,
    tags: ['японская', 'rock', 'активная'],
    description: null,
  },
  {
    embedId: 'T4RHuXd5pMg',
    score: 85,
    tags: ['японская', 'wagakki band', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: '3bBpiHJm3t0',
    score: 83,
    tags: ['японская', 'спокойная', 'караоке'],
    description: null,
  },
  {
    embedId: '64AaAySNROY',
    score: 81,
    tags: ['японская', 'спокойная', 'электронная', 'веселая'],
    description: null,
  },
  {
    embedId: '5qhBk_3OT-w',
    score: 82,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'mi0qVkGwmSw',
    score: 78,
    tags: ['японская', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: 'eRWy0HXN3wA',
    score: 63,
    tags: ['японская', 'спокойная'],
    description: null,
  },
  {
    embedId: 'K_xTet06SUo',
    score: 90,
    tags: ['японская', 'wagakki band', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: '8QPyFlJNmus',
    score: 60,
    tags: ['японская', 'активная'],
    description: null,
  },
  {
    embedId: 'X_k9qpsDm34',
    score: 90,
    tags: ['японская', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: 'sGYLIlCQWtw',
    score: 70,
    tags: ['японская', 'активная'],
    description: null,
  },
  {
    embedId: 'WBAIyY9y3HM',
    score: 89,
    tags: ['инструментальная', 'спокойная', 'электронная'],
    description: null,
  },
  {
    embedId: 'vgrogIrmMNk',
    score: 95,
    tags: ['инструментальная', 'sky mubs', 'грустная', 'спокойная'],
    description: (
      <Description>
        Я плачу... <br /> <Emoji src={PepeHands} />
      </Description>
    ),
  },
  {
    embedId: 'kx5-VXpTeU8',
    score: 88,
    tags: ['японская', 'вокалоид', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'WQYN2P3E06s',
    score: 71,
    tags: ['веселая', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'ceMVXr9puYk',
    score: 72,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: '2jGSRlXk8ag',
    score: 69,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'g-jGHbkM8e4',
    score: 68,
    tags: ['инструментальная', 'спокойная', 'веселая', 'кельтская', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'OWmNcmXZwfs',
    score: 100,
    tags: ['японская', 'kalafina', 'веселая', 'спокойная', 'yuki kajiura'],
    description: (
      <Description>
        Супер топ!
      </Description>
    ),
  },
  {
    embedId: 'Vr70GaeeQ3s',
    score: 79,
    tags: ['english', 'активная', 'rock'],
    description: null,
  },
  {
    embedId: '9ydC2pUQpNQ',
    score: 91,
    tags: ['японская', 'спокойная', 'грустная'],
    description: (
      <Description>
        Опенинг из <a target="_blank" href="https://shikimori.one/animes/2966-ookami-to-koushinryou">"Волчица и Пряности"</a>, 
        моя самая первая анимешка... <br /> <Emoji src={Sadeg} />
      </Description>
    ),
  },
  {
    embedId: '1_ozXudbN-4',
    score: 67,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'Qbff2TSZffg',
    score: 76,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'omsyef1qUvo',
    score: 73,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'YhS0emChH_8',
    score: 78,
    tags: ['инструментальная', 'спокойная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'Q2meWkWqc-I',
    score: 88,
    tags: ['японская', 'wagakki band', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'oVZ9nRAFR8s',
    score: 80,
    tags: ['инструментальная', 'спокойная', 'оркестровая'],
    description: null,
  },
  {
    embedId: '9gKu-FDBjy8',
    score: 78,
    tags: ['японская', 'активная', 'rock', 'yousei teikoku'],
    description: null,
  },
  {
    embedId: 'DaoyKECQnPw',
    score: 70,
    tags: ['инструментальная', 'оркестровая'],
    description: (
      <Description>
        Страшна вырубай. <br /> <Emoji src={monkaOMEGA} />
      </Description>
    ),
  },
  {
    embedId: 'Cty3jkKCD7I',
    score: 70,
    tags: ['english', 'активная', 'электронная', 'infected mushrooms'],
    description: null,
  },
  {
    embedId: 'Uzyii85rwqo',
    score: 78,
    tags: ['english', 'активная', 'электронная', 'infected mushrooms'],
    description: (
      <Description>
        С 2:50 крутяк!
      </Description>
    ),
  },
  {
    embedId: 'jTbCHkx5J0A',
    score: 76,
    tags: ['english', 'активная', 'электронная', 'infected mushrooms'],
    description: null,
  },
  {
    embedId: '-b8_89vlkaI',
    score: 78,
    tags: ['инструментальная', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'QLxEBMjqxus',
    score: 68,
    tags: ['инструментальная', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: 'nCaqf9WhqOY',
    score: 87,
    tags: ['японская', 'вокалоид', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: '1gFNk_L5R1w',
    score: 88,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: '8CNbrEBrAtA',
    score: 84,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'hGZL_5Wn3aQ',
    score: 89,
    tags: ['японская', 'активная', 'метал', 'ICCD'],
    description: null,
  },
  {
    embedId: 'aUWCrCXiVpA',
    score: 87,
    tags: ['english', 'rock', 'активная'],
    description: null,
  },
  {
    embedId: '5QfrrL1nZOw',
    score: 90,
    tags: ['японская', 'спокойная', 'rock', 'yousei teikoku'],
    description: null
  },
  {
    embedId: 'vHy81GG6k2o',
    score: 85,
    tags: ['english', 'rock', 'активная'],
    description: null,
  },
  {
    embedId: 'wjkhjFJbwrE',
    score: 82,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'NaRRYkw3vy8',
    score: 70,
    tags: ['инструментальная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'sesKiKYQn84',
    score: 81,
    tags: ['english', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: 'jhl5afLEKdo',
    score: 60,
    tags: ['японская', 'вокалоид' ],
    description: null,
  },
  {
    embedId: 'gfLcfLGzTsk',
    score: 82,
    tags: ['инструментальная', 'sky mubs', 'спокойная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'Dm95vTirBTI',
    score: 77,
    tags: ['инструментальная', 'sky mubs', 'спокойная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'MpSKn9URoCA',
    score: 84,
    tags: ['японская', 'метал', 'активная', 'ICCD'],
    description: null,
  },
  {
    embedId: 'o6wtDPVkKqI',
    score: 90,
    tags: ['японская', 'активная', 'веселая', 'караоке'],
    description: (
      <Description>
        Полезай в робота.
      </Description>
    ),
  },
  {
    embedId: 'xCkEsQXFv4g',
    score: 96,
    tags: ['russian', 'грустная', 'панк', 'элизиум', 'караоке'],
    description: (
      <Description>
        До слез... <br /> <Emoji src={PepeHands} />
      </Description>
    ),
  },
  {
    embedId: '59F9gY2OCO8',
    score: 80,
    tags: ['russian', 'король и шут', 'панк', 'активная'],
    description: null,
  },
  {
    embedId: 'QP0nAYAPAqM',
    score: 80,
    tags: ['russian', 'король и шут', 'панк', 'активная', 'караоке', 'веселая'],
    description: null,
  },
  {
    embedId: '_LNpvsoRgPY',
    score: 78,
    tags: ['russian', 'король и шут', 'панк', 'грустная'],
    description: null,
  },
  {
    embedId: 'dOAMvCyXXQo',
    score: 90,
    tags: ['японская', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: 'o1iz4L-5zkQ',
    score: 88,
    tags: ['японская', 'вокалоид', 'электронная', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'eMzsG9t66rE',
    score: 88,
    tags: ['японская', 'активная', 'веселая', 'rock'],
    description: null,
  },
  {
    embedId: 'az2Q7pjClYM',
    score: 80,
    tags: ['японская', 'активная', 'веселая', 'rock'],
    description: null,
  },
  {
    embedId: 'VJFNcHgQ4HM',
    score: 76,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'GSMV-Rv7C1w',
    score: 82,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'WRQGQyrytYU',
    score: 80,
    tags: ['english', 'nomy', 'rock', 'веселая'],
    description: null,
  },
  {
    embedId: 'P5QbkjnCvl4',
    score: 82,
    tags: ['english', 'nomy', 'караоке', 'rock'],
    description: null,
  },
  {
    embedId: 'tvKWfgqzQmY',
    score: 86,
    tags: ['english', 'nomy', 'караоке', 'rock'],
    description: null,
  },
  {
    embedId: 'bo7_D0s4fIc',
    score: 72,
    tags: ['russian', 'король и шут', 'панк', 'спокойная', 'караоке'],
    description: null,
  },
  {
    embedId: 'rIPOOoQxquE',
    score: 75,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'Mq6xQHInaHI',
    score: 77,
    tags: ['english', 'активная'],
    description: null,
  },
  {
    embedId: '1_D7kiOR9fA',
    score: 85,
    tags: ['японская', 'активная', 'веселая', 'rock'],
    description: null,
  },
  {
    embedId: '1iSTJYIXYao',
    score: 81,
    tags: ['english', 'активная', 'rock'],
    description: null,
  },
  {
    embedId: 'XCBi5kCbeNg',
    score: 88,
    tags: ['инструментальная', 'спокойная', 'классическая'],
    description: null,
  },
  {
    embedId: 'EVSb3dFszH4',
    score: 82,
    tags: ['инструментальная', 'спокойная', 'классическая'],
    description: null,
  },
  {
    embedId: 'u_xyg_s7gUA',
    score: 90,
    tags: ['инструментальная', 'спокойная', 'веселая', 'классическая'],
    description: null,
  },
  {
    embedId: 'L_iSDqqhsBg',
    score: 88,
    tags: ['инструментальная', 'активная', 'электронная'],
    description: (
      <Description>
        Очень хорошо сделано!
      </Description>
    ),
  },
  {
    embedId: 'WIqrKvfEJos',
    score: 80,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'kTHNpusq654',
    score: 68,
    tags: ['english', 'активная'],
    description: null,
  },
  {
    embedId: 'kZSmbObUzZA',
    score: 71,
    tags: ['активная', 'веселая'],
    description: null,
  },
  {
    embedId: '4CI3lhyNKfo',
    score: 62,
    tags: ['спокойная'],
    description: null,
  },
  {
    embedId: 'qrVSSTHXlAY',
    score: 57,
    tags: ['russian', 'спокойная'],
    description: null,
  },
  {
    embedId: '0gctXlUd9PQ',
    score: 70,
    tags: ['инструментальная', 'sky mubs', 'спокойная'],
    description: null,
  },
  {
    embedId: 'yHgIYfNF8kY',
    score: 80,
    tags: ['инструментальная', 'активная', 'электронная', 'хардкор/спидкор'],
    description: null,
  },
  {
    embedId: 'slVPS_VJqhs',
    score: 81,
    tags: ['японская', 'akatsuki records', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'lBasIGZC-JM',
    score: 78,
    tags: ['японская', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'wgBZylNg6U0',
    score: 70,
    tags: ['инструментальная', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: '9nqOgzyosU4',
    score: 85,
    tags: ['японская', 'спокойная'],
    description: null,
  },
  {
    embedId: 'shOhkzInW8s',
    score: 75,
    tags: ['инструментальная', 'активная', 'оркестровая'],
    description: null,
  },
  {
    embedId: 'WWGq-wlTLnk',
    score: 76,
    tags: ['russian', 'rock'],
    description: null,
  },
  {
    embedId: '61Elpj2DlnM',
    score: 78,
    tags: ['инструментальная', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'GMcWGqm4rOQ',
    score: 80,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: '92QCvMb6lx4',
    score: 80,
    tags: ['активная', 'love solfege'],
    description: null,
  },
  {
    embedId: '-3tMkLRbO3Y',
    score: 83,
    tags: ['russian', 'панк', 'активная', 'порнофильмы'],
    description: null,
  },
  {
    embedId: 'Cdsqx-djRH0',
    score: 81,
    tags: ['russian', 'rock', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'HMGetv40FkI',
    score: 79,
    tags: ['инструментальная', 'спокойная', 'классическая'],
    description: null,
  },
  {
    embedId: 'XhrRGi8PUHs',
    score: 85,
    tags: ['russian', 'егор летов', 'панк', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'FccIhsqXzdk',
    score: 87,
    tags: ['russian', 'егор летов', 'панк', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'osBPrU0k21s',
    score: 60,
    tags: ['russian', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: '4t5iAKrvzOs',
    score: 48,
    tags: ['russian'],
    description: null,
  },
  {
    embedId: 'Sv6dMFF_yts',
    score: 88,
    tags: ['english', 'спокойная', 'караоке'],
    description: null,
  },
  {
    embedId: 'X9Cb5nF92F4',
    score: 87,
    tags: ['японская', 'rock', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'cLBFxJmKsKg',
    score: 79,
    tags: ['english', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: '0EX3tQWswj0',
    score: 82,
    tags: ['японская', 'спокойная'],
    description: null,
  },
  {
    embedId: '8_opWKYPnHs',
    score: 83,
    tags: ['english', 'спокойная', 'грустная', 'караоке'],
    description: null,
  },
  {
    embedId: 'X6U_4DjgMao',
    score: 98,
    tags: ['english', 'twilight force', 'rock', 'активная', 'веселая', 'караоке'],
    description: null,
  },
  {
    embedId: 'vZ-FJXQK554',
    score: 91,
    tags: ['english', 'twilight force', 'rock', 'активная', 'веселая', 'караоке'],
    description: null,
  },
  {
    embedId: 't4TnTqH6E8M',
    score: 78,
    tags: ['russian', 'электронная'],
    description: null,
  },
  {
    embedId: 'VieIk9rjCos',
    score: 82,
    tags: ['инструментальная', 'mittsies', 'электронная'],
    description: null,
  },
  {
    embedId: 'K_7K7v2KGYU',
    score: 100,
    tags: ['инструментальная', 'mittsies', 'электронная', 'активная'],
    description: null,
  },
  {
    embedId: 'K_YbbAhRbIQ',
    score: 80,
    tags: ['инструментальная', 'mittsies', 'электронная'],
    description: null,
  },
  {
    embedId: 'aoP1KKlXbqI',
    score: 90,
    tags: ['инструментальная', 'mittsies', 'электронная'],
    description: null,
  },
  {
    embedId: 'EnDXGQmCz3U',
    score: 76,
    tags: ['инструментальная', 'mittsies', 'электронная'],
    description: null,
  },
  {
    embedId: '1vrEljMfXYo',
    score: 84,
    tags: ['english', 'караоке', 'веселая', 'спокойная'],
    description: null,
  },
  {
    embedId: 'SA_hw59NECE',
    score: 70,
    tags: ['инструментальная', 'активная', 'электронная'],
    description: null,
  },
  {
    embedId: 'GQz2MexCJSQ',
    score: 82,
    tags: ['russian', 'элизиум', 'панк', 'караоке', 'активная'],
    description: null,
  },
  {
    embedId: 'gnqXfK-ESoY',
    score: 84,
    tags: ['russian', 'караоке', 'rock', 'веселая'],
    description: null,
  },
  {
    embedId: '5GbSKaFf8Uc',
    score: 87,
    tags: ['russian', 'панк', 'порнофильмы', 'грустная', 'караоке'],
    description: null,
  },
  {
    embedId: 'C056vtZdQKc',
    score: 79,
    tags: ['russian', 'элизиум', 'панк', 'караоке', 'веселая'],
    description: null,
  },
  {
    embedId: 'Wsi36xSl8yM',
    score: 81,
    tags: ['японская', 'вокалоид', 'активная', 'rock'],
    description: null,
  },
  {
    embedId: 'iFnLGhDSJpw',
    score: 78,
    tags: ['инструментальная', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'FxKtRmODwFk',
    score: 90,
    tags: ['russian', 'панк', 'порнофильмы', 'активная', 'караоке'],
    description: null,
  },
  {
    embedId: 'sAhvAuC8JJU',
    score: 89,
    tags: ['russian', 'панк', 'порнофильмы', 'активная', 'караоке'],
    description: null,
  },
  {
    embedId: 'MNmLn6a-jqw',
    score: 87,
    tags: ['english', 'веселая', 'активная', 'караоке'],
    description: null,
  },
  {
    embedId: 'KrFX_NG3GS0',
    score: 89,
    tags: ['russian', 'электронная', 'хардкор/спидкор', 'караоке'],
    description: null,
  },
  {
    embedId: 'LPRO3EzMQv0',
    score: 91,
    tags: ['инструментальная', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'LpheaI374Ic',
    score: 50,
    tags: ['инструментальная', 'грустная', 'спокойная', 'классическая'],
    description: null,
  },
  {
    embedId: 'Voz24mnv7CI',
    score: 68,
    tags: ['активная'],
    description: null,
  },
  {
    embedId: 'iJ4f2UfLyoU',
    score: 72,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'GZLuk3SK-3k',
    score: 70,
    tags: ['russian', 'егор летов', 'панк', 'активная', 'грустная'],
    description: null,
  },
  {
    embedId: '7VAoZXwDSpw',
    score: 70,
    tags: ['японская', 'активная'],
    description: null,
  },
  {
    embedId: 'hEvLtFnbF7c',
    score: 68,
    tags: ['японская', 'активная'],
    description: null,
  },
  {
    embedId: '5kz1c1bvKMQ',
    score: 80,
    tags: ['японская', 'yuki kajiura', 'спокойная'],
    description: null,
  },
  {
    embedId: 'Lcr5Mc6dGxI',
    score: 89,
    tags: ['english', 'rock', 'веселая', 'активная', 'twilight force'],
    description: null,
  },
  {
    embedId: 'O4irXQhgMqg',
    score: 77,
    tags: ['english', 'грустная', 'спокойная', 'rock'],
    description: null,
  },
  {
    embedId: 'mTCESSzPZSw',
    score: 80,
    tags: ['японская', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'apRLsd4W6gM',
    score: 87,
    tags: ['японская', 'rigël theatre', 'спокойная', 'веселая', 'кельтская'],
    description: null,
  },
  {
    embedId: 'uifv1yxYcOU',
    score: 86,
    tags: ['японская', 'rigël theatre', 'спокойная', 'веселая'],
    description: null,
  },
  {
    embedId: 'm9RW5DYNrvU',
    score: 84,
    tags: ['инструментальная', 'rigël theatre', 'активная', 'веселая', 'кельтская'],
    description: null,
  },
  {
    embedId: 'bYjaufqKT6E',
    score: 89,
    tags: ['russian', 'егор летов', 'панк', 'грустная', 'спокойная', 'караоке'],
    description: null,
  },
  {
    embedId: 'bTkIdiG0QmQ',
    score: 78,
    tags: ['russian', 'егор летов', 'панк', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'jP9JIBG0SZ8',
    score: 81,
    tags: ['russian', 'егор летов', 'панк', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: '6CSTPhPrTuQ',
    score: 89,
    tags: ['russian', 'егор летов', 'панк', 'караоке', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'uXq_Le2Awxk',
    score: 87,
    tags: ['russian', 'элизиум', 'панк', 'караоке', 'грустная', 'активная'],
    description: null,
  },
  {
    embedId: 'Urjm6FwRy6g',
    score: 93,
    tags: ['russian', 'элизиум', 'панк', 'караоке'],
    description: null,
  },
  {
    embedId: 'mtegWEn8LT8',
    score: 91,
    tags: ['russian', 'элизиум', 'панк', 'караоке'],
    description: null,
  },
  {
    embedId: '250rS-RvwlU',
    score: 59,
    tags: ['инструментальная', 'phyxinon', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'RQzUQ291l_c',
    score: 82,
    tags: ['russian', 'панк', 'король и шут', 'веселая'],
    description: null,
  },
  {
    embedId: 'uyL37Ox5Qxs',
    score: 64,
    tags: ['инструментальная', 'активная'],
    description: null,
  },
  {
    embedId: 'V3OPDTwH9os',
    score: 86,
    tags: ['english', 'активная', 'веселая'],
    description: null,
  },
  {
    embedId: 'RtTYQuO1j6w',
    score: 75,
    tags: ['японская', 'akatsuki records', 'веселая'],
    description: null,
  },
  {
    embedId: '3GSY_jRiOdw',
    score: 76,
    tags: ['японская', 'веселая', 'активная'],
    description: null,
  },
  {
    embedId: '5nwEfGzbRok',
    score: 65,
    tags: ['english', 'rock', 'грустная'],
    description: null,
  },
  {
    embedId: 'Qh2yzh4VoMs',
    score: 69,
    tags: ['инструментальная', 'xi', 'спокойная'],
    description: null,
  },
  {
    embedId: '5jJU-pLjdzc',
    score: 73,
    tags: ['инструментальная', 'xi', 'электронная'],
    description: null,
  },
  {
    embedId: 'vatcanQQJvQ',
    score: 81,
    tags: ['инструментальная', 'xi', 'электронная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'AQEv4xdRvGM',
    score: 80,
    tags: ['японская', 'метал', 'активная', 'ICCD'],
    description: null,
  },
  {
    embedId: 'LD3baPUqa2E',
    score: 88,
    tags: ['японская', 'метал', 'активная', 'ICCD'],
    description: null,
  },
  {
    embedId: '89Bp0dpd2Rs',
    score: 73,
    tags: ['инструментальная', 'электронная', 'активная'],
    description: null,
  },
  {
    embedId: '-DywnutP7Fw',
    score: 80,
    tags: ['russian', 'егор летов', 'панк', 'спокойная', 'грустная'],
    description: null,
  },
  {
    embedId: 'k0NY8xP5IdQ',
    score: 88,
    tags: ['russian', 'панк', 'спокойная', 'грустная', 'караоке'],
    description: null,
  },
  {
    embedId: '7HYcLccP77Y',
    score: 79,
    tags: ['russian', 'панк', 'король и шут', 'грустная'],
    description: null,
  },
  {
    embedId: 'PfakLoNEmn0',
    score: 79,
    tags: ['russian', 'rock', 'грустная', 'спокойная'],
    description: null,
  },
  {
    embedId: 'HN_Suv1w2oM',
    score: 81,
    tags: ['russian', 'панк', 'король и шут', 'караоке'],
    description: null,
  },
  {
    embedId: 'D8HqRH5cHPo',
    score: 89,
    tags: ['russian', 'панк', 'караоке', 'грустная'],
    description: null,
  },
  {
    embedId: 'QFFrkZOYojk',
    score: 90,
    tags: ['инструментальная', 'классическая'],
    description: null,
  },
  {
    embedId: 'NqAOGduIFbg',
    score: 94,
    tags: ['инструментальная', 'классическая', 'активная'],
    description: null,
  },
  {
    embedId: '4Tr0otuiQuU',
    score: 88,
    tags: ['инструментальная', 'классическая'],
    description: null,
  },
  {
    embedId: 'FVTXlRxVdEY',
    score: 87,
    tags: ['инструментальная', 'классическая'],
    description: null,
  },
  {
    embedId: '_4IRMYuE1hI',
    score: 86,
    tags: ['инструментальная', 'классическая'],
    description: null,
  },
  {
    embedId: 'B9zRToy-mwk',
    score: 87,
    tags: ['инструментальная', 'классическая', 'спокойная'],
    description: null,
  },
  {
    embedId: 'cKkDMiGUbUw',
    score: 90,
    tags: ['инструментальная', 'классическая'],
    description: null,
  },
];

// todo: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
let a = {
"cKkDMiGUbUw": "Strauss ~ The Blue Danube Waltz",
"B9zRToy-mwk": "Tchaikovsky ~ Dance of the Sugar Plum Fairy",
"_4IRMYuE1hI": "Beethoven's 5th Symphony",
"FVTXlRxVdEY": "A Little Night Music - Wolfgang Amadeus Mozart",
"4Tr0otuiQuU": "Beethoven - Moonlight Sonata (FULL)",
"NqAOGduIFbg": "Antonio Vivaldi - Storm",
"QFFrkZOYojk": "Вивальди - Времена Года - Зима ( Antonio Vivaldi )",
"D8HqRH5cHPo": "Ляпис Трубецкой - Воины Света -",
"HN_Suv1w2oM": "Король и Шут - Камнем по голове",
"PfakLoNEmn0": "Ария - Беспечный Ангел",
"7HYcLccP77Y": "Король и Шут - Прыгну со скалы",
"k0NY8xP5IdQ": "Ляпис Трубецкой - Шут",  
"-DywnutP7Fw": "Беспонтовый пирожок",  
"89Bp0dpd2Rs": "Night of Knights Sakuya'sTheme (Flowering Night remix)　ナイト・オブ・ナイツ",
"7VAoZXwDSpw": "Gomenne, Iikoja Irarenai",
"1bJEjHk0BGk": "Road of Resistance",
"2Od7QCsyqkE": "【MV】鈴木雅之『DADDY ! DADDY ! DO ! feat. 鈴木愛理』TVアニメ「かぐや様は告らせたい？～天才たちの恋愛頭脳戦～」OP主題歌",
"2jGSRlXk8ag": "VOICE",
"3bBpiHJm3t0": "Sailor Moon OST - Moonlight Densetsu",
"4oPM8zTeois": "【Deemo】Marigold 弾いてみた",
"5kKnrjeDUqw": "gmtn (witch's slave) -  furioso melodia",
"5nReJMJGrRE": "Madoka Magica: The Movie OST - Odd World #3",
"5qhBk_3OT-w": "Fractal Dreamers - Scarlet Night",
"6IkuV_lZtiI": "No Game No Life Zero OST   I truly love you「Original Soundtrack」",
"6fILxnBH1Tg": "Dragonborn",
"7EEUU-yIN5c": "【初音ミク】「マジカルミライ 2019」ライブ映像 － ブレス・ユア・ブレス / 和田たけあき【Hatsune Miku \"Magical Mirai 2019\"】",
"8QPyFlJNmus": "心臓を捧げよ！",
"8nxuNiRJKRg": "Halozy - Kikoku Doukoku Jigokuraku",
"64AaAySNROY": "Scarlet Ballet",
"-I--cdqDbdU": "【オリジナル Ethnic】 SPÏKA 「Rigël Theatre」",
"-RAeuWxOif4": "Natsume Chiaki - Hanairo Biyori",
"-wILF0YwvNM": "Kalafina - Hikari No Senritsu",
"BG746QmRgqk": "Rigel Theatre - Erlija Gate",
"BgQ8sa0HPtQ": "【東方Vocal／Irish Folk】 Adieu, to this Lively Graveyard 「Akatsuki Records」 【Subbed】",
"Bjadoqjdz2c": "Nomy (Official) - Cocaine (Original Version)",
"DN-Dcwq4i2g": "Divinity: Original Sin 2 OST - Main Theme (Full)",
"EJYKsY0Vcts": "Made in Abyss Opening Full『Deep in Abyss』メイドインアビス【ENG Sub】",
"EmWOznX2uUQ": "Back in Control",
"F8t5mR6AmK8": "M2U - Placebo Dying",
"FQs9cV0jycg": "Anima",
"FqCw7gCTZQs": "乙女どもよ。／CHiCO with HoneyWorks",
"M-r44DVnbSE": "NieR : Automata OST - Grandma (Destruction)",
"HbNUR1P0fTM": "∆MAX (deltaMAX)",
"IB1URcYIaOE": "Low Roar - Don't Be So Serious",
"IWEpkRoxK0o": "t+pazolite - Call me it. (500 Tortures)",
"JxFUY7Ka8e0": "Foul Play ni Kurari",
"K_xTet06SUo": "和楽器バンド / 千本桜",
"Kkgp1-fHn6Y": "Tatsh - \"IMAGE -MATERIAL- (Version 0)\"",
"M92c6pl10u0": "ピノキオピー- おばけのウケねらい feat. 初音ミク / Ghosts Play to the Audience",
"N_O7wkUmLqs": "Now (Connor)",
"N_SWfKjvlvw": "Helblinde - Elder Hymn",
"Pn7dCgtwX2c": "Linked Horizon - Guren No Yumiya (Attack On Titan) FULL Opening Theme HQ",
"PstkKL72mw0": "【Love solfege】石塔のカルテシア",
"S-Nll_HapuU": "【Deemo】Leviathan 弾いてみた",
"Sq_q5MIIYX4": "Dancing in the Tavern",
"SrEHyYlJjVA": "eXceed3rd-JADE PENETRATE-BLACK PACKAGE OST ~ Intersect Thunderbolt",
"T4RHuXd5pMg": "鈴華ゆう子with和楽器バンド / 六兆年と一夜物語",
"U1oeOZVtA84": "【初音ミク】「マジカルミライ 2018」ライブ映像 － グリーンライツ・セレナーデ / Omoi feat. 初音ミク【Hatsune Miku \"Magical Mirai 2018\"】",
"U4LcyjRFDds": "[HD] Hatsune Miku: Live Concert - Cat food (English Subs)",
"UWwzmed9Z5U": "こだまことだま",
"W6I1xm49Lpw": "killy killy JOKER",
"WBAIyY9y3HM": "\"Shona\" by Jake Chudnow [HD]",
"WQYN2P3E06s": "Christopher Tin - Sogno di Volare (\"The Dream of Flight\") (Civilization VI Main Theme)",
"XTedaWpPjto": "Phillip Phillips - Raging Fire (Lyric Video)",
"X_k9qpsDm34": "Shiori",
"XbRPOR19p_c": "angela「騎士行進曲」Music Clip",
"Yzjum7CgQqw": "Yooh - Dynasty -al fine-",
"ZZvJY7_gyfw": "[Official Video] Yousei Teikoku - Kuusou Mesorogiwi - 空想メソロギヰ 妖精帝國",
"ZwfjS5CvedM": "Kalafina - Heavenly Blue Music Video",
"aEHxqBHCkFc": "",
"ady--PNMsfI": "NIER OST - Song of the Ancients ~ Fate",
"b1bXu0XZDlU": "Kalafina - To the Beginning",
"bAZuZjMD7lE": "Mirai",
"bE0hDymkLsQ": "love solfege - Emeth Azur",
"by_dL99tndw": "【MODEL DL】【MMD】 Ai no Uta / 愛の詩 by Lamaze-P【YYB Miku Futura】",
"cOe9RPqg1GE": "Sana - Packet Hero",
"ceMVXr9puYk": "Sparkling Daydream",
"dPLKc5tdvo0": "love solfege - protomimesis#14",
"dkCMpHF27fo": "kimi to dareka no yasashisa ni",
"eJhCAnjz8ZA": "Hatsune Miku - Dream Fever [ENG SUB] [HD] (Live at Magical Mirai 2013)",
"eRWy0HXN3wA": "Secret Sky",
"f3ESZSrKvkI": "【Deemo】Entrance 弾き直してみた",
"fr26k_KusS4": "OVERLAPPERS",
"g-jGHbkM8e4": "Fantasy Celtic Music - Spirit of the Wild",
"iQp9iud9u0I": "【シノアリスOST】鏖殺ノ饗宴 (Banquet Of Massacre)",
"jO4fTcziVRM": "XI - Akasha",
"k-3y2LVF_SE": "Freedom Dive",
"kv4UD4ICd_0": "Rigël Theatre - Lurie (Album: Älvorna -Memories of Abcense-)",
"kx5-VXpTeU8": "SlowMotion | Hatsune Miku Magical Mirai 2016 (Sub Rom/Esp)",
"lkicMsn-s_8": "UNDEAD CORPORATION - Everything will freeze",
"lvRw5Kjx31o": "answer",
"mcywsWmHEVc": "Aimai Hertz (Nisekoi)",
"mi0qVkGwmSw": "Secret of goddess The god World Only Know.",
"nSDgHBxUbVQ": "Ed Sheeran - Photograph (Official Music Video)",
"oozQ4yV__Vw": "Phillip Phillips - Gone, Gone, Gone",
"pTRgr9IWLnY": "Mezame",
"pV1DT5JlRlc": "ALTIMA",
"q-v-a-NFH-Q": "Hellogoodbye - Finding Something To Do [New Song]",
"qO8AoYPnr68": "Dance of curse",
"sGYLIlCQWtw": "【艦これボーカル】 帝國交響楽団 - 燃え落ちる誇り -Counter raid Another D- 【Subbed】",
"srhni4w2TbI": "アイデンティティ",
"swZd3u6voNE": "love solfege ft.真名辺あや - matricaria",
"t4XycIIfA6A": "Lost in Time",
"va810QKC1S0": "A Story Untold",
"vgrogIrmMNk": "Sky Mubs - Beyond Heavens",
"vw2-PDXs2zY": "love solfege - クレプスクルムの林檎",
"w0dU7NyfN_A": "croiX - Team Grimoire (Full Version)",
"wDIzGjLwKBM": "Love Solfege - Babel",
"wExQLV7Ndps": "Lite Show Magic   Crack traxxxx",
"xHq-TEluOrM": "HoMM3 - Necropolis Town Theme (cover)",
"yql9xh5UaIw": "Nomy (Official) - You better die young",
"zycqjvKFiHU": "[M3 2017] 753. x ABSOLUTE CASTAWAY - 祭果ての花 (Matsuri hate no hana)",
"_4BLiOP1aaY": "BUMP OF CHICKEN「ray」",
"_IY95itIKis": "Rinn Ding Dong - Rigel Theatre",
"0EX3tQWswj0": "佐々木恵梨『ふゆびより』 (Music Video) TVアニメ「ゆるキャン」EDテーマ",
"0gctXlUd9PQ": "Sky Mubs - A Journey to Dreams",
"1_D7kiOR9fA": "【東方Vocal／Traditional Rock】 「心綺楼」 「凋叶棕」 【ENG Subs】",
"1_ozXudbN-4": "Team Grimoire - C18H27NO3",
"1bJEjHk0BGk": "Road of Resistance",
"1gFNk_L5R1w": "Helblinde - The Solace of Oblivion",
"1iSTJYIXYao": "Red Like Roses Part 1+2 Complete",
"1vrEljMfXYo": "John Denver - Take Me Home, Country Roads (Audio)",
"2Od7QCsyqkE": "【MV】鈴木雅之『DADDY ! DADDY ! DO ! feat. 鈴木愛理』TVアニメ「かぐや様は告らせたい？～天才たちの恋愛頭脳戦～」OP主題歌",
"2jGSRlXk8ag": "VOICE",
"3bBpiHJm3t0": "Sailor Moon OST - Moonlight Densetsu",
"4CI3lhyNKfo": "Bella Ciao - ORIGINALE",
"4_ANxTOG_Xk": "Divinity: Original Sin 2 OST -  Mead, Gold & Blood (Ifan's Theme)",
"4oPM8zTeois": "【Deemo】Marigold 弾いてみた",
"4t5iAKrvzOs": "Крылатые качели",
"5GbSKaFf8Uc": "Я так соскучился",
"5QfrrL1nZOw": "Yousei Teikoku - Wahrheit",
"5kKnrjeDUqw": "gmtn (witch's slave) -  furioso melodia",
"5nReJMJGrRE": "Madoka Magica: The Movie OST - Odd World #3",
"5qhBk_3OT-w": "Fractal Dreamers - Scarlet Night",
"6IkuV_lZtiI": "No Game No Life Zero OST   I truly love you「Original Soundtrack」",
"6fILxnBH1Tg": "Dragonborn",
"7EEUU-yIN5c": "【初音ミク】「マジカルミライ 2019」ライブ映像 － ブレス・ユア・ブレス / 和田たけあき【Hatsune Miku \"Magical Mirai 2019\"】",
"8CNbrEBrAtA": "Torikago トリカゴ - XX:me (Lyrics) (Darling In the Franxx opening)",
"8QPyFlJNmus": "心臓を捧げよ！",
"8_opWKYPnHs": "The Moon Rises",
"8nxuNiRJKRg": "Halozy - Kikoku Doukoku Jigokuraku",
"9gKu-FDBjy8": "妖精帝國 Yousei Teikoku - The Creator",
"9nqOgzyosU4": "【Grimms Notes】 Wasureji no Kotonoha (忘れじの言の葉) ft. KanaChi 【Hereson】",
"9ydC2pUQpNQ": "旅の途中",
"59F9gY2OCO8": "Камнем по голове",
"61Elpj2DlnM": "Tom Odell - Another Love (Official Instrumental Audio)",
"64AaAySNROY": "Scarlet Ballet",
"92QCvMb6lx4": "【Love solfege】La Tempesta",
"-3tMkLRbO3Y": "Чужое горе",
"-I--cdqDbdU": "【オリジナル Ethnic】 SPÏKA 「Rigël Theatre」",
"-RAeuWxOif4": "Natsume Chiaki - Hanairo Biyori",
"-b8_89vlkaI": "Isabella's Lullaby",
"-wILF0YwvNM": "Kalafina - Hikari No Senritsu",
"BG746QmRgqk": "Rigel Theatre - Erlija Gate",
"BgQ8sa0HPtQ": "【東方Vocal／Irish Folk】 Adieu, to this Lively Graveyard 「Akatsuki Records」 【Subbed】",
"Bjadoqjdz2c": "Nomy (Official) - Cocaine (Original Version)",
"C056vtZdQKc": "Elysium / Элизиум ft Таня Малая ☆ Взлётная полоса ☆ Stadium Live",
"Cdsqx-djRH0": "Штиль",
"Cty3jkKCD7I": "The Legend of the Black Shawarma",
"DN-Dcwq4i2g": "Divinity: Original Sin 2 OST - Main Theme (Full)",
"DaoyKECQnPw": "Bloodborne OST - The Hunter",
"Dm95vTirBTI": "Sky Mubs - Strike Into Hells [Legendary Edition]",
"EJYKsY0Vcts": "Made in Abyss Opening Full『Deep in Abyss』メイドインアビス【ENG Sub】",
"EVSb3dFszH4": "Swan Lake - II. Dance of the Little Swans - Part 3/8",
"EmWOznX2uUQ": "Back in Control",
"EnDXGQmCz3U": "Mittsies - Vitality",
"F8t5mR6AmK8": "M2U - Placebo Dying",
"FQs9cV0jycg": "Anima",
"FqCw7gCTZQs": "乙女どもよ。／CHiCO with HoneyWorks",
"FxKtRmODwFk": "Перемены",
"GMcWGqm4rOQ": "水瀨祈『夢的花蕾』MUSIC VIDEO（中文字幕版）",
"GQz2MexCJSQ": "Ад наш!",
"GSMV-Rv7C1w": "Halozy - Genryuu Kaiko",
"HMGetv40FkI": "Merry Go Round of Life - Howl's Moving Castle (Joe Hisaishi)",
"HbNUR1P0fTM": "∆MAX (deltaMAX)",
"IB1URcYIaOE": "Low Roar - Don't Be So Serious",
"IWEpkRoxK0o": "t+pazolite - Call me it. (500 Tortures)",
"JxFUY7Ka8e0": "Foul Play ni Kurari",
"K_7K7v2KGYU": "Mittsies - Titanium",
"K_YbbAhRbIQ": "Mittsies - Epitomize",
"K_xTet06SUo": "和楽器バンド / 千本桜",
"Kkgp1-fHn6Y": "Tatsh - \"IMAGE -MATERIAL- (Version 0)\"",
"KrFX_NG3GS0": "Будущего нет",
"L_iSDqqhsBg": "Calamity Fortune",
"M92c6pl10u0": "ピノキオピー- おばけのウケねらい feat. 初音ミク / Ghosts Play to the Audience",
"MNmLn6a-jqw": "The Wellerman (Gingertail Cover)",
"MpSKn9URoCA": "黄泉より聴こゆ、皇国の燈と焔の少女。",
"Mq6xQHInaHI": "Lone Digger",
"N_O7wkUmLqs": "Now (Connor)",
"N_SWfKjvlvw": "Helblinde - Elder Hymn",
"NaRRYkw3vy8": "Welcome to Fort Joy",
"OWmNcmXZwfs": "Kalafina - Symphonia (Video Clip)",
"P5QbkjnCvl4": "Nomy - You Better Die Young w/lyrics",
"Pn7dCgtwX2c": "Linked Horizon - Guren No Yumiya (Attack On Titan) FULL Opening Theme HQ",
"PstkKL72mw0": "【Love solfege】石塔のカルテシア",
"Q2meWkWqc-I": "【和楽器バンド】天樂 Tengaku 【VOCALOID】",
"QLxEBMjqxus": "The Queen's High Seas (Tavern Version)",
"QP0nAYAPAqM": "Кукла колдуна",
"Qbff2TSZffg": "Grimoire of Darkness",
"S-Nll_HapuU": "【Deemo】Leviathan 弾いてみた",
"SA_hw59NECE": "Black Tiger Sex Machine x Lektrique - Death",
"Sq_q5MIIYX4": "Dancing in the Tavern",
"SrEHyYlJjVA": "eXceed3rd-JADE PENETRATE-BLACK PACKAGE OST ~ Intersect Thunderbolt",
"Sv6dMFF_yts": "Fun.: We Are Young ft. Janelle Monáe [OFFICIAL VIDEO]",
"T4RHuXd5pMg": "鈴華ゆう子with和楽器バンド / 六兆年と一夜物語",
"U1oeOZVtA84": "【初音ミク】「マジカルミライ 2018」ライブ映像 － グリーンライツ・セレナーデ / Omoi feat. 初音ミク【Hatsune Miku \"Magical Mirai 2018\"】",
"U4LcyjRFDds": "[HD] Hatsune Miku: Live Concert - Cat food (English Subs)",
"UWwzmed9Z5U": "こだまことだま",
"Uzyii85rwqo": "Saeed",
"VJFNcHgQ4HM": "黒皇帝 - Galaxy Collapse",
"VieIk9rjCos": "Mittsies - Alchemy",
"Vr70GaeeQ3s": "Symphony of the Night",
"W6I1xm49Lpw": "killy killy JOKER",
"WBAIyY9y3HM": "\"Shona\" by Jake Chudnow [HD]",
"WIqrKvfEJos": "yuikonnu - Caramel Heaven",
"WQYN2P3E06s": "Christopher Tin - Sogno di Volare (\"The Dream of Flight\") (Civilization VI Main Theme)",
"WRQGQyrytYU": "Nomy - Last forever / Lyrics",
"WWGq-wlTLnk": "Ya Svoboden",
"Wsi36xSl8yM": "Hatsune Miku - Talent Shredder [HQ]",
"X6U_4DjgMao": "Flight of the Sapphire Dragon",
"X9Cb5nF92F4": "ELFENSJóN（エルフェンシオン）『緋灼の魔女』フル ver.",
"XCBi5kCbeNg": "Wolfgang Amadeus Mozart (Моцарт) - Турецкий марш",
"XTedaWpPjto": "Phillip Phillips - Raging Fire (Lyric Video)",
"X_k9qpsDm34": "Shiori",
"XbRPOR19p_c": "angela「騎士行進曲」Music Clip",
"XhrRGi8PUHs": "Без меня",
"YhS0emChH_8": "Kenji Kawai - Tenchi Hou Take",
"Yzjum7CgQqw": "Yooh - Dynasty -al fine-",
"ZZvJY7_gyfw": "[Official Video] Yousei Teikoku - Kuusou Mesorogiwi - 空想メソロギヰ 妖精帝國",
"ZwfjS5CvedM": "Kalafina - Heavenly Blue Music Video",
"aEHxqBHCkFc": "恋は渾沌の隷也　歌詞付き",
"aUWCrCXiVpA": "Dragonforce - Valley of the Damned",
"ady--PNMsfI": "NIER OST - Song of the Ancients ~ Fate",
"aoP1KKlXbqI": "Mittsies - Sanctuary",
"az2Q7pjClYM": "【東方Vocal／Traditional Rock】 祭符「神遊びの唄」 「凋叶棕」【ENG Subs】",
"b1bXu0XZDlU": "Kalafina - To the Beginning",
"bAZuZjMD7lE": "Mirai",
"bE0hDymkLsQ": "love solfege - Emeth Azur",
"bo7_D0s4fIc": "Марионетки",
"by_dL99tndw": "【MODEL DL】【MMD】 Ai no Uta / 愛の詩 by Lamaze-P【YYB Miku Futura】",
"cLBFxJmKsKg": "Lullaby for a Princess",
"cOe9RPqg1GE": "Sana - Packet Hero",
"ceMVXr9puYk": "Sparkling Daydream",
"dOAMvCyXXQo": "しちごさん。×ABSOLUTE CASTAWAY - 楽園図 (Album: Cross bouquet)",
"dPLKc5tdvo0": "love solfege - protomimesis#14",
"dkCMpHF27fo": "kimi to dareka no yasashisa ni",
"eJhCAnjz8ZA": "Hatsune Miku - Dream Fever [ENG SUB] [HD] (Live at Magical Mirai 2013)",
"eMzsG9t66rE": "【東方 Vocal / Trance】 Halozy ~ Deconstruction Star 【Comiket 77】",
"eRWy0HXN3wA": "Secret Sky",
"f3ESZSrKvkI": "【Deemo】Entrance 弾き直してみた",
"fr26k_KusS4": "OVERLAPPERS",
"g-jGHbkM8e4": "Fantasy Celtic Music - Spirit of the Wild",
"gfLcfLGzTsk": "Sky Mubs - Now You believe in You",
"gnqXfK-ESoY": "Земляне - Трава у дома",
"hGZL_5Wn3aQ": "Imperial Circus Dead Decadence - Uta",
"iFnLGhDSJpw": "A Lonely Strain",
"iQp9iud9u0I": "【シノアリスOST】鏖殺ノ饗宴 (Banquet Of Massacre)",
"jO4fTcziVRM": "XI - Akasha",
"jTbCHkx5J0A": "The Pretender",
"jhl5afLEKdo": "【Hatsune Miku】 World is Mine / ryo（supercell）【初音ミク】",
"k-3y2LVF_SE": "Freedom Dive",
"kTHNpusq654": "Katy Perry - Hot N Cold (Official)",
"kZSmbObUzZA": "PUPO   Gelato Al Cioccolato",
"kv4UD4ICd_0": "Rigël Theatre - Lurie (Album: Älvorna -Memories of Abcense-)",
"kx5-VXpTeU8": "SlowMotion | Hatsune Miku Magical Mirai 2016 (Sub Rom/Esp)",
"lBasIGZC-JM": "Halozy - Sentimental Skyscraper",
"lkicMsn-s_8": "UNDEAD CORPORATION - Everything will freeze",
"lvRw5Kjx31o": "answer",
"mcywsWmHEVc": "Aimai Hertz (Nisekoi)",
"mi0qVkGwmSw": "Secret of goddess The god World Only Know.",
"nCaqf9WhqOY": "[1080P Full風] The Snow White Princess is 白い雪のプリンセスは - 初音ミク Hatsune Miku DIVA Arcade English Romaji",
"nSDgHBxUbVQ": "Ed Sheeran - Photograph (Official Music Video)",
"o1iz4L-5zkQ": "八王子P 「気まぐれメルシィ  feat. 初音ミク」(6/15発売Best AL「Eight」収録）",
"o6wtDPVkKqI": "「残酷な天使のテーゼ」MUSIC VIDEO（HDver.）/Zankoku na Tenshi no Te-ze“The Cruel Angel's Thesis”",
"oVZ9nRAFR8s": "The City Must Survive",
"omsyef1qUvo": "TEMPEST",
"oozQ4yV__Vw": "Phillip Phillips - Gone, Gone, Gone",
"osBPrU0k21s": "Эдуард Хиль - Зима",
"pTRgr9IWLnY": "Mezame",
"pV1DT5JlRlc": "ALTIMA",
"q-v-a-NFH-Q": "Hellogoodbye - Finding Something To Do [New Song]",
"qO8AoYPnr68": "Dance of curse",
"qrVSSTHXlAY": "Прекрасное далёко",
"rIPOOoQxquE": "t+pazolite - CENSORED!!",
"sAhvAuC8JJU": "Система",
"sGYLIlCQWtw": "【艦これボーカル】 帝國交響楽団 - 燃え落ちる誇り -Counter raid Another D- 【Subbed】",
"sesKiKYQn84": "Set It Off - Why Worry (Official Video)",
"shOhkzInW8s": "Heroes of Might and Magic III - Battle Theme - Cover by Dryante",
"slVPS_VJqhs": "【東方ヴォーカルPV】KARMANATIONS【暁Records公式】",
"srhni4w2TbI": "アイデンティティ",
"swZd3u6voNE": "love solfege ft.真名辺あや - matricaria",
"t4TnTqH6E8M": "DEAD BLONDE - Мальчик на девятке (Official Audio)",
"t4XycIIfA6A": "Lost in Time",
"tvKWfgqzQmY": "Nomy - Cocaine w/lyrics",
"u_xyg_s7gUA": "J.S. Bach - Badinerie ( Suite No.2 )",
"vHy81GG6k2o": "Equilibrium - Waldschrein",
"vZ-FJXQK554": "Guardian of the Seas",
"va810QKC1S0": "A Story Untold",
"vgrogIrmMNk": "Sky Mubs - Beyond Heavens",
"vw2-PDXs2zY": "love solfege - クレプスクルムの林檎",
"w0dU7NyfN_A": "croiX - Team Grimoire (Full Version)",
"wDIzGjLwKBM": "Love Solfege - Babel",
"wExQLV7Ndps": "Lite Show Magic   Crack traxxxx",
"wgBZylNg6U0": "t+pazolite - Cheatreal",
"wjkhjFJbwrE": "Kano - Walk this way / English lyrics",
"xCkEsQXFv4g": "Дети мишени / Дети убийцы",
"xHq-TEluOrM": "HoMM3 - Necropolis Town Theme (cover)",
"yHgIYfNF8kY": "t+pazolite - Oshama Scramble! (Uncut Edition)",
"yql9xh5UaIw": "Nomy (Official) - You better die young",
"zycqjvKFiHU": "[M3 2017] 753. x ABSOLUTE CASTAWAY - 祭果ての花 (Matsuri hate no hana)",
"_4BLiOP1aaY": "BUMP OF CHICKEN「ray」",
"_IY95itIKis": "Rinn Ding Dong - Rigel Theatre",
"_LNpvsoRgPY": "Отражение",
"3GSY_jRiOdw": "Hanatan - Airman ga Taosenai (Sound Holic Ver) (NO GAMEPLAY)",
"5jJU-pLjdzc": "Halcyon",
"5kz1c1bvKMQ": "【神曲】and I'm home（歌詞付き） まどマギAボーナス中楽曲",
"5nwEfGzbRok": "My Funeral",
"6CSTPhPrTuQ": "Мёртвые",
"250rS-RvwlU": "【Deemo】Wings of piano (FULL) 弾いてみた",
"AQEv4xdRvGM": "腐蝕ルサンチマン,不死欲の猿楽座。",
"GZLuk3SK-3k": "Убивать",
"LD3baPUqa2E": "Imperial Circus Dead Decadence - Gekiai no Yobigoe ga Dekiai no Kyougoe wo",
"LPRO3EzMQv0": "MiddleIsland - Delrio",
"Lcr5Mc6dGxI": "Rise of a Hero",
"LpheaI374Ic": "MiddleIsland ~ Roze",
"O4irXQhgMqg": "The Rolling Stones - Paint It, Black (Official Lyric Video)",
"Qh2yzh4VoMs": "ハッピーエンドオブザワールド",
"RQzUQ291l_c": "Танец злобного гения",
"RtTYQuO1j6w": "【東方ヴォーカルPV】Necromantic【暁Records公式】",
"Urjm6FwRy6g": "Когда мы были младше",
"V3OPDTwH9os": "Kuba Oms - My Love (Official Lyric Video)",
"Voz24mnv7CI": "Aquaphobia",
"apRLsd4W6gM": "Lengsel (feat. ミーウェル)",
"bTkIdiG0QmQ": "Долгая счастливая жизнь",
"bYjaufqKT6E": "Отряд не заметил потери бойца",
"hEvLtFnbF7c": "Liar Mask",
"iJ4f2UfLyoU": "promise",
"jP9JIBG0SZ8": "Вселенская большая любовь",
"m9RW5DYNrvU": "Rigël Theatre - La Sylphide",
"mTCESSzPZSw": "Eir Aoi - Ignite",
"mtegWEn8LT8": "Всё и ничего…",
"uXq_Le2Awxk": "Ради чего?",
"uifv1yxYcOU": "Riness - Ghosts of Memories - (feat. ミーウェル)",
"uyL37Ox5Qxs": "The Dynasty",
"vatcanQQJvQ": "Blue Zenith",
"FccIhsqXzdk": "Далеко бежит дорога (Впереди веселья много)",
}

export const videos = rawVideos
  .map(v => ({ ...v, title: a[v.embedId] }))
  .sort((a, b) => b.score - a.score)

const doesVideoMatchTags = (tags, video) => {
  const { "ⓘ": hasDescription, ...restTags } = tags;
  const { description, tags: videoTags } = video; 

  if ((description === null) === hasDescription) 
    return false;
  for (const [tagName, value] of Object.entries(restTags))
    if (!videoTags.includes(tagName) === value)
      return false;

  return true;
};
export const getVideosByTags = (tags) => videos.filter(video => doesVideoMatchTags(tags, video));
